package com.cloudvault.core.service;

import com.cloudvault.core.dto.ShareLinkRequest;
import com.cloudvault.core.dto.ShareLinkResponse;
import com.cloudvault.core.model.File;
import com.cloudvault.core.model.Folder;
import com.cloudvault.core.model.ShareLink;
import com.cloudvault.core.model.WorkspaceRole;
import com.cloudvault.core.repository.FileRepository;
import com.cloudvault.core.repository.FolderRepository;
import com.cloudvault.core.repository.ShareLinkRepository;
import com.cloudvault.common.exception.BadRequestException;
import com.cloudvault.common.exception.ForbiddenException;
import com.cloudvault.common.exception.ResourceNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.LocalDateTime;
import java.util.UUID;

@Service
public class ShareService {

    private static final Logger log = LoggerFactory.getLogger(ShareService.class);

    private final ShareLinkRepository shareLinkRepository;
    private final FileRepository fileRepository;
    private final FolderRepository folderRepository;
    private final WorkspaceService workspaceService;
    private final PasswordEncoder passwordEncoder;

    public ShareService(ShareLinkRepository shareLinkRepository, FileRepository fileRepository,
                        FolderRepository folderRepository, WorkspaceService workspaceService,
                        PasswordEncoder passwordEncoder) {
        this.shareLinkRepository = shareLinkRepository;
        this.fileRepository = fileRepository;
        this.folderRepository = folderRepository;
        this.workspaceService = workspaceService;
        this.passwordEncoder = passwordEncoder;
    }

    @Transactional
    public ShareLinkResponse createShareLink(ShareLinkRequest request, UUID creatorId) {
        if (request.getFileId() == null && request.getFolderId() == null) {
            throw new BadRequestException("Either fileId or folderId must be provided to share");
        }

        File file = null;
        Folder folder = null;
        UUID workspaceId = null;

        if (request.getFileId() != null) {
            file = fileRepository.findByIdAndIsDeleted(request.getFileId(), false)
                    .orElseThrow(() -> new ResourceNotFoundException("File not found"));
            workspaceId = file.getWorkspace().getId();
        } else {
            folder = folderRepository.findByIdAndIsDeleted(request.getFolderId(), false)
                    .orElseThrow(() -> new ResourceNotFoundException("Folder not found"));
            workspaceId = folder.getWorkspace().getId();
        }

        // Verify sharing user has read access (VIEWER/EDITOR/OWNER)
        workspaceService.getWorkspaceRole(workspaceId, creatorId);

        String accessToken = UUID.randomUUID().toString().replace("-", "") + UUID.randomUUID().toString().replace("-", "");

        String passwordHash = null;
        if (StringUtils.hasText(request.getPassword())) {
            passwordHash = passwordEncoder.encode(request.getPassword());
        }

        LocalDateTime expiresAt = null;
        if (request.getExpiresAtDays() != null && request.getExpiresAtDays() > 0) {
            expiresAt = LocalDateTime.now().plusDays(request.getExpiresAtDays());
        }

        ShareLink shareLink = ShareLink.builder()
                .file(file)
                .folder(folder)
                .creatorId(creatorId)
                .accessToken(accessToken)
                .passwordHash(passwordHash)
                .expiresAt(expiresAt)
                .downloadLimit(request.getDownloadLimit() != null ? request.getDownloadLimit() : -1)
                .downloadCount(0)
                .permissionLevel(request.getPermissionLevel() != null ? request.getPermissionLevel().toUpperCase() : "VIEWER")
                .build();

        ShareLink savedShare = shareLinkRepository.save(shareLink);
        log.info("Share link generated by creator {} for accessToken: {}", creatorId, accessToken);

        return mapToShareResponse(savedShare);
    }

    @Transactional
    public ShareLinkResponse resolveShareLink(String accessToken, String password) {
        ShareLink shareLink = shareLinkRepository.findByAccessToken(accessToken)
                .orElseThrow(() -> new ResourceNotFoundException("Share link not found"));

        // Check Expiration
        if (shareLink.getExpiresAt() != null && shareLink.getExpiresAt().isBefore(LocalDateTime.now())) {
            shareLinkRepository.delete(shareLink);
            throw new ResourceNotFoundException("Share link has expired");
        }

        // Check Download Limits
        if (shareLink.getDownloadLimit() != -1 && shareLink.getDownloadCount() >= shareLink.getDownloadLimit()) {
            throw new ForbiddenException("Download limit exceeded for this share link");
        }

        // Check Passcode Protection
        if (shareLink.getPasswordHash() != null) {
            if (!StringUtils.hasText(password) || !passwordEncoder.matches(password, shareLink.getPasswordHash())) {
                throw new ForbiddenException("Invalid share passcode");
            }
        }

        // Increment access counter
        shareLink.setDownloadCount(shareLink.getDownloadCount() + 1);
        ShareLink updatedShare = shareLinkRepository.save(shareLink);

        return mapToShareResponse(updatedShare);
    }

    public ShareLinkResponse mapToShareResponse(ShareLink share) {
        return ShareLinkResponse.builder()
                .id(share.getId())
                .fileId(share.getFile() != null ? share.getFile().getId() : null)
                .folderId(share.getFolder() != null ? share.getFolder().getId() : null)
                .creatorId(share.getCreatorId())
                .accessToken(share.getAccessToken())
                .expiresAt(share.getExpiresAt())
                .downloadLimit(share.getDownloadLimit())
                .downloadCount(share.getDownloadCount())
                .permissionLevel(share.getPermissionLevel())
                .isPasswordProtected(share.getPasswordHash() != null)
                .createdAt(share.getCreatedAt())
                .build();
    }
}
